# Generated by Django 2.1 on 2019-07-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='college',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='college',
            field=models.ManyToManyField(to='rsearch.College'),
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='company',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='company',
            field=models.ManyToManyField(to='rsearch.Company'),
        ),
    ]
