# Generated by Django 2.1 on 2019-07-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsearch', '0002_auto_20190713_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='collegeName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyName',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='degreeName',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skillName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
