# Generated by Django 2.1 on 2019-07-14 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsearch', '0003_auto_20190713_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='college',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rsearch.College'),
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='company',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rsearch.Company'),
        ),
    ]
