# Generated by Django 2.1 on 2019-07-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsearch', '0004_auto_20190714_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='college',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='college',
            field=models.ManyToManyField(to='rsearch.College'),
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='company',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='company',
            field=models.ManyToManyField(to='rsearch.Company'),
        ),
    ]
