# Generated by Django 2.1 on 2019-07-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsearch', '0005_auto_20190714_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='college',
            field=models.ManyToManyField(blank=True, to='rsearch.College'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='company',
            field=models.ManyToManyField(blank=True, to='rsearch.Company'),
        ),
    ]
